############################################################
# Docker Compose for PXE and xenial64
# 
############################################################
version: "2"

services:
  tftp:
    image: pghalliday/tftp
    volumes:
      # Mount netboot 
      - /media/cdrom/install/netboot/:/var/tftpboot/pxe
      # Mount kernel boot parameters
      - ./xenial64/linux-boot:/var/tftpboot/pxe/pxelinux.cfg/default:ro
    network_mode: host
    depends_on:
          - "dhcp"

  dhcp:
    image: networkboot/dhcpd
    volumes:
      - ./dhcpd.conf:/data/dhcpd.conf
    network_mode: host
    command: enp0s8

  http:
    image: httpd:2.4.25-alpine
    ports:
      - "80:80"
    volumes:
      # Serving ISO in iso/ to allow mounting more directories
      - /media/cdrom:/usr/local/apache2/htdocs/iso:ro
      # Mounting preseed file
      - ./xenial64/preseed.cfg:/usr/local/apache2/htdocs/preseed.cfg:ro
      # Mounting default sources.list
      - ./xenial64/sources.list:/usr/local/apache2/htdocs/conf/apt/sources.list:ro

    network_mode: host
    depends_on:
          - "tftp"
