- name: Add alias for Docker
  lineinfile:
    dest: ~/.bash_aliases
    line: "alias d='/usr/bin/docker'"
    owner: "{{ ansible_ssh_user }}"
    regexp: ^alias d='.*/docker'$
    state: present
    insertafter: EOF
    create: True
  become: False

- name: Add alias for Docker Compose
  lineinfile:
    dest: ~/.bash_aliases
    line: "alias dc='/usr/local/bin/docker-compose'"
    owner: "{{ ansible_ssh_user }}"
    regexp: ^alias dc='.*/docker\-compose'$
    state: present
    insertafter: EOF
    create: True
  become: False