- name: Start PSQL
  service: 
    name: postgresql
    state: started

- name: Reload PSQL
  service: 
    name: postgresql
    state: reloaded

- name: Restart PSQL
  service: 
    name: postgresql
    state: restarted