- name: Download tfenv
  git:
    repo: https://github.com/kamatama41/tfenv.git
    dest: ~/.tfenv
  become: False

- name: Links to /usr/local/bin
  file: 
    src: /home/{{ ansible_ssh_user }}/.tfenv/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - tfenv
    - terraform

- name: Install latest terraform
  command: tfenv install 0.11.11
  become: False

- name: Add alias for Terraform
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/.bash_aliases
    line: "alias tf='/usr/local/bin/terraform'"
    owner: "{{ ansible_ssh_user }}"
    regexp: ^alias tf='/usr/local/bin/terraform'$'
    state: present
    insertafter: EOF
    create: True
  become: False