############################################################
# Docker Compose for Ansible with a target machine
# 
############################################################
version: "2"

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: cgarciaarano/homelab:ansible
    volumes:
      - ./etc:/etc/ansible/
      - ./ssh_keys/id_rsa:/root/.ssh/id_rsa

  target:
    build:
      context: .
      dockerfile: xenial/Dockerfile
    image: cgarciaarano/homelab:target
