############################################################
# Docker Compose for Ansible with a target machine
# 
############################################################
version: "2"

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: cgarciaarano/homelab:ansible
    environment:
      - ANSIBLE_DEBUG=False
      - ANSIBLE_VERBOSITY=2
      - ANSIBLE_ROLES_PATH=/opt/ansible/roles
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - ./etc:/etc/ansible/
      - ./ssh_keys/:/root/.ssh/
      - .:/opt/ansible

  target:
    build:
      context: .
      dockerfile: xenial/Dockerfile
    image: cgarciaarano/homelab:target

