############################################################
# Docker Compose for Ansible with a target machine
# 
############################################################
version: "2"

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: cgarciaarano/homelab:ansible
    volumes:
      - ./hosts:/etc/ansible/hosts

  target:
    build:
      context: xenial/
      dockerfile: Dockerfile
    image: cgarciaarano/homelab:target
