############################################################
# Docker Compose for Ansible with a target machine
# 
############################################################
version: "2"

services:
  ansible:
    build:
      context: docker
      dockerfile: Dockerfile
    image: cgarciaarano/homelab:ansible
    environment:
      - ANSIBLE_DEBUG=False
      - ANSIBLE_VERBOSITY=2
      - ANSIBLE_ROLES_PATH=/etc/ansible/roles
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - ~/.ssh/:/root/.ssh/

  target:
    build:
      context: .
      dockerfile: xenial/Dockerfile
    image: cgarciaarano/homelab:target

