- name: Add PSQL Repository
  apt_repository: 
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' 
    state: present

- name: Authenticate repo
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  register: aptauth

- name: Install PSQL
  apt: 
    pkg: "{{ item }}"
    state: present
    update_cache: true
  with_items: ["postgresql-{{ version }}"]
  notify:
    - Start PSQL

- name: Setup postgresql.conf
  template: 
    src: postgresql.conf.j2 
    dest: "{{ configpath }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify:
    - Restart PSQL

- name: Setup pg_hba.conf
  template: 
    src: pg_hba.conf.j2 
    dest: "{{ configpath }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - Reload PSQL

- name: Install psycopg2
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: ["python-psycopg2"]

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: Setup admin user
  postgresql_user: 
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    role_attr_flags: SUPERUSER
    expires: infinity
  become: yes
  become_user: postgres
